### ISSUE TITLE
Strange behaviour of surface generation in `GriddedSplineSurface`

### ISSUE THREAD

**Issue by alisterburt** [morphometrics/morphosamplers#15]
### Description

hey @brisvag, just playing with the `GriddedSplineSurface` - I have some test points defined on parallel planes and the surface generation is kinda crazy

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7307488/213759154-2a97c9bb-ccc6-4b28-9d95-b64f21349878.png">

What do you think? The points aren't perfect but they're definitely not too bad either

side note: I would expect the mesh generated by the `mesh()` method to only cover the annotated points, not the entire extended grid, do you agree?

simple repro:

```python
import numpy as np
import napari

from morphosamplers.surface_spline import GriddedSplineSurface

points = [np.array([[32.        , 12.11278271,  8.57706584],
       [32.        ,  7.93396208, 24.73249253],
       [32.        ,  6.11561802, 43.45429729],
       [32.        , 10.39169565, 51.42048109]]), np.array([[23.2004918 , 13.83377781, 51.58485539],
       [23.2004918 , 11.62575967, 45.66435473],
       [23.2004918 , 10.48069118, 33.00382345],
       [23.2004918 , 13.7314471 , 20.09001775],
       [23.2004918 , 15.8541391 ,  6.97826341]]), np.array([[17.64685761, 25.35482086, 54.474294  ],
       [17.64685761, 21.42696069, 44.2354204 ],
       [17.64685761, 22.06684847, 42.83124131],
       [17.64685761, 24.28672785, 32.97439732],
       [17.64685761, 23.00598426, 21.47863839],
       [17.64685761, 26.90304258,  6.42403983]]), np.array([[12.59433764, 45.02032012, 46.99249561],
       [12.59433764, 43.84638583, 37.64672635],
       [12.59433764, 44.39229356, 32.61933003],
       [12.59433764, 44.23961388, 21.32151976]])]

surface = GriddedSplineSurface(points=points, separation=1)
viewer = napari.Viewer(ndisplay=3)
viewer.add_surface(surface.mesh())
viewer.add_points(np.concatenate(points, axis=0))
napari.run()
```

**Comment by alisterburt** [comment]
interesting - definitely not always strange, would be good to pin down exactly what makes it break and see if we can make it more robust 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7307488/213764422-01753644-03fc-42f1-9ddc-42851a438b58.png">

**Comment by brisvag** [comment]
Bizarre! Definitely something going wrong, and I didn't see this in my testing... Will play with it some time soon and see if I can pinpoint the issue!

**Comment by brisvag** [comment]
> side note: I would expect the mesh generated by the mesh() method to only cover the annotated points, not the entire extended grid, do you agree?

Like with points and orientations, I optted to give the full thing by default and provide the `Surface.mask` so you can mask out things as needed. You should be able to simply mask the vertices with 
```py
valid = points[mask]
```
And I guess in principle if you discard all faces containing points that were masked out it will Just Work? Something like
```py
invalid = points[~mask]
valid_faces = np.isin(invalid, faces)...
```
 Or something along those lines. Sorry, not at PC!

**Comment by alisterburt** [comment]
Cool! Thanks for the tips

There will definitely be a more elegant way to do it but the following works for getting the masked surface

```python
vertices, faces = surface.mesh()
valid_faces = np.all(np.isin(faces, np.argwhere(surface.mask)), axis=1)
faces = faces[valid_faces]
```

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7307488/213785944-cc3aa7fb-e92c-44a3-927a-db1b5dc23fbd.png">

**Comment by brisvag** [comment]
Nice! I guess it'd be nice to not get that staircase effect there, which is quite ugly. I think that requires quite some work tho :P

**Comment by brisvag** [comment]
> What do you think? The points aren't perfect but they're definitely not too bad either

Preddy odd; what I understand so far is that, for some reason, when the first set of splines is generate (the ones to oversample the manual picking), their `u` is set wrongly, so that when sampling `u=0` and `u=1` you don't get the first and last original points, but you end up way overshooting the last point! But why this would happen only in this case, not clue yet :/

**Comment by brisvag** [comment]
Acutally, I was wrong, those points are fine. What goes wrong are 2 different things.

The first and main issue is that you picked the first line of points in the *opposite* direction as the rest, and there is currently no mechanism to flip it around, so it stays flipped, which messes up the surface construction.

The second is inside `minimize_point_row_pair_distance` calculation: when the line is flipped around, the best "pair distance" is when there is only single point of overlap between one line and the next. This exacerbates the issue by adding a bunch of points later when the splines are extended. This might actually come up in other corner cases, so it may be wise to somehow downwight results that have very little overlap.

But solving the first issue (iberting the first line of points) is enough to get a correct result:

![image](https://user-images.githubusercontent.com/23482191/214041241-d80783ee-d244-4a1c-bb80-895f8c96553a.png)

**Comment by alisterburt** [comment]
thanks for digging! have added #17 to fix - you want to take it or should I implement if I want it?

**Comment by brisvag** [comment]
Feel free to take a stab at it, I'm not planning to do it soon. If you do, I suggest you start from `minimize_point_row_pair_distance`: in principle you should be able to loop over the annotation first one way, then the other, and I think you should get a good result.

However, I fear you'll still get some cases where the surface "explodes", because currently we simply average all the distances at each offset, and take the smallest... So if the edges of the row of points happen to be close to each other, they will overpower the proper overlap. So we really need a way to "prefer" more overlap over less.

However, we need a smart way to do it that can preserve partial overlaps such as this:

```
------oooooooo
oooooooooo----
```

Now that I read what I just wrote, I'm not sure it's understandable xD Feel free to call me if you want a less gibberish explanation :P
